### ISSUE TITLE
15-minute settlement period support

### ISSUE THREAD

**Issue by klubalo** [rnovacek/homeassistant_cz_energy_spot_prices#52]
Any new about this?

EN: https://www.ote-cr.cz/en/documentation/electricity-documentation/information-to-switch-to-15-min-interval
CZ: https://www.ote-cr.cz/cs/dokumentace/dokumentace-elektrina/15minut

**Comment by rnovacek** [comment]
If I understand it right (and correct me here please), those changes doesn't affect SPOT electricity trading for us end users for now. One of the presentations on OTE pages linked above says:

> Granularita produktů na DT zůstává od 1. 7. 2024 beze změny – na DT bude možno obchodovat pouze 60min. produkty (možnost obchodovat 60min. a 15min. produkty se očekává až od Q1/2025)

So there will be an option to use 15min products from Q1 next year. For now, we'll continue to use DT (denní trh = daily market) with 60min period.

**Comment by iBobik** [comment]
@rnovacek What are you plans about it?

I am going to move to the spot now, so propably I will not have option to trade hourly.

**Comment by rnovacek** [comment]
No plans at the moment, sorry, patches welcomed :)

The presentation in the CZ link above says that 60 minutes products should still be available on the market, so maybe check some providers to see what's on the market currently.

I don't have a lot of time to work on this integration at the moment and this would probably require significant changes to the way the integration works. I'll probably wait for this change to go live, but if someone wants to start working on it now, I'm happy to accept PRs.

**Comment by iBobik** [comment]
Thank you for reply. I will consider PR.

**Comment by Paja-git** [comment]
> The change at OTE should go live on 1st October: https://www.ote-cr.cz/cs/o-spolecnosti/zpravy_ote/ridici-vybor-pro-propojeni-trhu-potvrzuje-termin-zavedeni-15minutoveho-obchodniho-intervalu-na-jednotnem-dennim-trhu-selektrinou-na-30-zari-2025

There will be 2 products since Oct 1st: spot60 (the current one) and Spot15. The Spot60 hour price will be the average from 4 Spot15s for the given hour, e.g. 10:00-11:00 = AVG(10:15, 10:30,10:45,11:00).
I didnt notice any message about the API change, so I'd expect that the integration will continue to work as usual. 
There will be just a publishing time shift. The spot prices are published at 12:57 currently, the new time is expected at 13:02.

**Comment by Paja-git** [comment]
> Thanks for the info guys. Are there any end-user offers with the 15min interval? If not, I think we still have some time to implement this. Unless someone beats me to it, I'll just wait for October to see how the new API looks.
> 
> > There will be just a publishing time shift. The spot prices are published at 12:57 currently, the new time is expected at 13:02.
> 
> I think this might be worth implementing soon. It now downloads the new prices every hour at :00, so with this change, it'll be delayed by almost whole hour.

Sorry, I didn't notice, but found now some details. see my edited comment few mins ago. https://www.ote-cr.cz/cs/dokumentace/xsd-wsdl-manual-pubweb/uzivatelsky-manual_webove_sluzby_ote_g.pdf

**Comment by rnovacek** [comment]
No worries, thanks for the link, that's very helpful. So we do need to make change before Oct 1. `GetDamPriceE` -> `GetDamPricePeriodE`. Those two APIs looks quite similar. We'll need to add new config option to switch between 15min and 60min reporting, but the API call can be the same for both (according to the example when requesting 15min prices using `PT15M`, it also contains 60min prices in `HourlyPrice`.

We'll need to support both APIs in the integration for some period. Problem is that the new GetDamPricePeriodE doesn't work yet and I was not able to find out if there is a testing environment...

**Comment by Mira141** [comment]
> Thanks for the info guys. Are there any end-user offers with the 15min interval?

Yes, I called my spot- trader Bidli now and answer is, that since today they account spot in 15 minutes . According to it, 15-min granularity for programming HA is wery welcome ... Thanks for all your work !

**Comment by lukasokoun** [comment]
> GetDamPricePeriodE

How do I turn this on please?

**Comment by lukasokoun** [comment]
Yes, I have the latest version 0.7.5, I'm not interested in finding the cheapest windows, I'm fine with them if I have the data here after 15 minutes, but I don't have them :(

<img width="840" height="1456" alt="Image" src="https://github.com/user-attachments/assets/caf9f45d-f4f4-4ae9-a787-92db08533f4b" />

**Comment by Paja-git** [comment]
> How sensor sensor.current_spot_electricity_price and it's derivatives, sensor.current_sell_electricity_price and sensor.current_buy_electricity_price will look like? 

I'd expect the same sensor structure. The OTE source data identifies trading periods in that way, e.g. period 1 - 0:00-0:15, period 2 0:15-0:30 and so on.  The future version will be configurable to get 15 or 60min data, AFAIK.

**Comment by petrd1** [comment]
Hi, if it wouldn't be a complication, I would really appreciate a version that can read 15 minute intervals even without all the accompanying sensors. Their implementation based on 15 minute intervals could perhaps be in the next version. Thank you.

**Comment by OooKGit** [comment]
EFG green energy starts from 1.10, ener spot month later. Would be nice to get 15 slots and same granularity order(1-4x24), those additional sensors are not very useful anyway. Always better to use order, based on required grid import (buying, so take lowest) or export (selling, so highest). Thank you guys for all your work and fast adaptation to new api

**Comment by rnovacek** [comment]
I plan to support 1 hour intervals as long as they are offered by OTE. Likely there will be a switch in the settings between 1 hour and 15 minute interval.

**Comment by Mira141** [comment]
According to requests on energy suppliers, they still account 1-hour intervals for end users. I asked my "bidli" provider and they answered in e-mail, that 15-minutes interval accounting is planned since 1. Jan 2026.  It seems is depends individually on energy provider, then request your provider, when he will make change.  Important is not what OTE annonced and presents since 1.10.2025, but what your energy suplier really accounts.  It depends individual ...

**Comment by petrd1** [comment]
Hello @rnovacek, could you please estimate when the new version will be distributed?

If the implementation is difficult due to additional sensors, would it be possible to consider a version where 15 minute intervals would be available? (I don't use additional sensors, but I would need to implement 15 minute intervals into my larger solution.) Thank you very much.

**Comment by rnovacek** [comment]
I'm quite close to finishing a beta version. I really hope to have it ready by tomorrow, but no promises.

**Comment by rnovacek** [comment]
Beta version [0.8.0b1](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/releases/tag/0.8.0b1) is ready for testing. All feedback is welcome.

**Comment by iBobik** [comment]
> Beta version [0.8.0b1](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/releases/tag/0.8.0b1) is ready for testing. All feedback is welcome.

Great, just installed it (existing config, using it only for rendering chart on dashboard).

After restart it was failing:

<img width="640" height="412" alt="Image" src="https://github.com/user-attachments/assets/1203fe15-437e-4dcb-a92c-3322475ec14b" />
Logs:
```
Logger: homeassistant.config_entries
Zdroj: config_entries.py:761
První výskyt: 11:47:16 (1 výskyt)
Naposledy logováno: 11:47:16

Error setting up entry Electricity Spot Rate in CZK/kWh for cz_energy_spot_prices
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/__init__.py", line 60, in async_setup_entry
    commodity = Commodity(config_entry.data[CONF_COMMODITY])
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'commodity'
```


So I tried to remove integration config and created it again, now it loaded correctly.

Then I had to update the chart config like this:
```diff
  series:
-  - entity: sensor.current_spot_electricity_price
+  - entity: sensor.current_spot_electricity_price_15min
```

**Comment by rnovacek** [comment]
@iBobik Thanks for testing. The error is fixed in 0.8.0b2. Changing the chart config is to be expected as 60min intervals are still supported and it's the default option.

**Comment by Paja-git** [comment]
It is already there:
binary_sensor.spot_electricity_has_tomorrow_data.
Do you have fresh data for tomorrow?

**Comment by matomatusov** [comment]
Hi, after updating to beta version 0.8.0b3, I get a message when I click configure. The integration shows me the original version 0.7.6. I don't see 15 minute intervals.

<img width="1246" height="748" alt="Image" src="https://github.com/user-attachments/assets/be6a6d86-254a-43ae-b8c5-9a23e3084387" />

**Comment by rnovacek** [comment]
@matomatusov Given the traceback says `template_entity`, could I also ask for the buy/sell templates from your config?

**Comment by rnovacek** [comment]
@matomatusov This template code is not part of the spot prices integration. There's now a built-in way to compute buy/sell prices. I would suggest you migrate to that.

Nevertheless this doesn't explain the "500 Internal Server Error". That seems to come from the integration. Is there anything about that in the logs?

**Comment by matomatusov** [comment]
Hi, Thanks for the correction. Do you know why the 15 minute intervals for today 28.10, were not loaded? Only the intervals from yesterday, 27.10, were loaded.

<img width="613" height="963" alt="Image" src="https://github.com/user-attachments/assets/ebdb5ee7-a9af-4078-985e-7fab72c45763" />

**Comment by Paja-git** [comment]
Update to b5 version. Lot of fixes was done. Then wait for 13:10, if OTE will publish on time.

**Comment by Paja-git** [comment]
It looks you still have some old set of data, based on the *_2 name.  I see the similar error when 2 services (15,60min) created. The error is  just a cosmetic one, IMHO.
```Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:843
integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 4:01:43 PM (1 occurrence)
Last logged: 4:01:43 PM

Platform cz_energy_spot_prices does not generate unique IDs. ID spot_electricity_has_tomorrow_data is already used by binary_sensor.spot_electricity_has_tomorrow_data - ignoring binary_sensor.spot_electricity_has_tomorrow_data```

**Comment by Paja-git** [comment]
@JarKol Input number here. Zero, if no blocks are needed. 

<img width="588" height="688" alt="Image" src="https://github.com/user-attachments/assets/efa59d28-934e-4409-b1a8-2b8b65dcf111" />

**Comment by matomatusov** [comment]
Hi, my data from OTE didn't load today.

Logger: custom_components.cz_energy_spot_prices.coordinator
Zdroj: helpers/update_coordinator.py:424
integrace: Spotové ceny energií v Česku (dokumentace, problémy)
První výskyt: 13:11:33 (1 výskyt)
Naposledy logováno: 13:11:33

Error fetching Czech Energy Spot Prices [SpotRateCoordinator] for electricity data: Failed to update OTE prices


------------------------------------------------------------------------------------------------------------------------------------

Logger: homeassistant.components.binary_sensor
Zdroj: helpers/entity_platform.py:843
integrace: Binární senzor (dokumentace, problémy)
První výskyt: 23:01:52 (1 výskyt)
Naposledy logováno: 23:01:52

Platform cz_energy_spot_prices does not generate unique IDs. ID spot_electricity_has_tomorrow_data is already used by binary_sensor.spot_electricity_has_tomorrow_data_2 - ignoring binary_sensor.spot_electricity_has_tomorrow_data

**Comment by michalk-k** [comment]
Yep.
yesterday, "tomorrow" data hasnt been fetched

```
2025-11-01 13:10:39.005 WARNING (MainThread) [custom_components.cz_energy_spot_prices.coordinator] Failed to update OTE prices, will retry in 1 seconds: 
2025-11-01 13:10:39.006 ERROR (MainThread) [custom_components.cz_energy_spot_prices.coordinator] Error fetching Czech Energy Spot Prices [SpotRateCoordinator] for electricity data: Failed to update OTE prices
2025-11-01 13:10:40.008 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.13/asyncio/base_events.py:2051: RuntimeWarning: coroutine 'DataUpdateCoordinator.async_request_refresh' was never awaited
  handle = None  # Needed to break cycles when an exception occurs.
```

And then since subsequent midnight:

```
2025-11-02 00:00:01.040 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 851, in on_schedule
    self.async_set_updated_data(data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 527, in async_set_updated_data
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/cz_energy_spot_prices/spot_rate_mixin.py", line 60, in _handle_coordinator_update
    self.update(self.coordinator.data)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/binary_sensor.py", line 184, in update
    window = trade_rates.cheapest_windows[self.hours]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: None
2025-11-02 00:00:01.068 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 287, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 368, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 491, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 807, in _source_updated
    self.async_set_updated_data(data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 527, in async_set_updated_data
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/cz_energy_spot_prices/spot_rate_mixin.py", line 60, in _handle_coordinator_update
    self.update(self.coordinator.data)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/binary_sensor.py", line 184, in update
    window = trade_rates.cheapest_windows[self.hours]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: None
```


BTW manual realoading of the integration helps to load current prices

**Comment by rnovacek** [comment]
Thanks for reporting. The error when OTE fails to update should be fixed in 0.8.0b6.

@michalk-k What problem do you see with the 15min_order sensor? It's a key-value dictionary, where key is ISO datetime and value is a pair: interval order, price.

**Comment by Paja-git** [comment]
If I've got your idea well, it is already there for cheapest ones. Just define the 1 hour block for 15min config. The average price (mean) is an attribute of the given block sensor.

**Comment by Donach** [comment]
> Would it be possible to add a sensor that would have 15 min intervals ordered/sorted in the attributes for 24 hours from, let say, 6 pm of the given day to 6 pm of the next day? The point is that (especially in winter) prices can be cheap before midnight, but even cheaper after midnight. Therefore, in certain seasons of the year, it would be better to use this type of sensor that does not start according to the human day, but with the period of the most expensive prices.

What is your usecase here?
You could not rely on such sensor anyway, since there is always a time (0-12:30 or13:30, or whenever OTE publishes DAM prices), where you don't know prices for the next day 0-6...

**Comment by rnovacek** [comment]
> Hi, I really need to work with 15 minute prices. I downloaded version 0.8.0b6 but I still only see hourly prices which are no longer valid. What am I doing wrong? Thank you

You need to add a new service with 15min prices:


| <img width="1036" height="439" alt="Image" src="https://github.com/user-attachments/assets/d6870760-603e-4653-8ecd-cbd77e00ef80" /> | <img width="430" height="608" alt="Image" src="https://github.com/user-attachments/assets/a3448b12-8d29-4b1c-9dca-3a9730ff0c7d" /> | <img width="421" height="311" alt="Image" src="https://github.com/user-attachments/assets/5e135af5-9a75-439b-873e-0f1c3fd02e74" /> |
|---|---|---|

**Comment by Paja-git** [comment]
60mins sebsirs are preserved. For 15min - add new service.

**Comment by Lipown** [comment]
I am on latest beta since I found out our energy seller switched to 15 minutes intervals as of 1/1 without any email noticed. Though I kept both 1h and 15minutes services. 1h are not loading properly now - I need to hit a reload button and same happened this midnight for 15minutes prices. Anybody has advise for solution of that? Heaters are triggered also based on price so they were not working during night and my mother had very terrible cold morning :(

**Comment by Paja-git** [comment]
I experienced the similar on 1/1/2026. I've changed the buy templates to reflect new prices on 31/12 late afternoon and no afternoon  update on 1/1. The service reload w/o effect. After the HA restart everything was (and is) OK.

**Comment by Lipown** [comment]
@rnovacek  sorry for lot of another errors there :)

[home-assistant_cz_energy_spot_prices_2026-01-09T10-56-15.124Z.log](https://github.com/user-attachments/files/24525531/home-assistant_cz_energy_spot_prices_2026-01-09T10-56-15.124Z.log)

**Comment by rnovacek** [comment]
> Hi, i have instaled it, but i got only 8 sensor.

You need to set up sell/buy template to get more sensors.

**Comment by michalk-k** [comment]
Spis az nebudou. 
V devtools jsi vloz "spot"  do pole nad sloupcem nazvu entit. Vyjedou ti vsechny entity s timto nazev. A muzes pohledem overit jaka data jsou nebo chybi. 

<img width="1135" height="844" alt="Image" src="https://github.com/user-attachments/assets/88cbd960-6ddc-4066-8b65-c039dce5b5a6" />

Doporucuji take zapnout debug pro tuto integraci. Treba se se pak v logu neco objevi v dobe kdy se maji data stahovat.

<img width="1826" height="557" alt="Image" src="https://github.com/user-attachments/assets/4b636692-1d03-402f-94b7-feccb358a406" />

**Comment by Lipown** [comment]
@Paja-git  @michalk-k - pár bodů
1) Nemuzu stopro rict, ze to dela jen kvuli te beta, nemam vytvorit specificke vlakno (at tu to nespinim :))?
2) Hnedka to udelam. Predpokladam, ze vystup muzu postnout hnedka odpo po ocekavane aktualizaci zitrejsich cen

**Comment by michalk-k** [comment]
entity se same neobjevi.
Musis znovu pridat "spot integraci" v HA a tam zvolis 15min profil.

Jinak proc nestahnout tu betu pomoci HACS? neni to totozne s "povolenim". proste jednorazove si stahnes verzi jakou chces.

**Comment by LadCZ** [comment]
Ano mám, znovu jsem ji přeinstaloval. Ale když dám 0, tak projde bez erroru a hodnota se poníží, takže vyřešeno :-)

<img width="533" height="762" alt="Image" src="https://github.com/user-attachments/assets/b63450ed-9c04-4536-9a0d-9412216eb2c5" />

**Comment by rnovacek** [comment]
Vyřešeno, zavírám.
