### ISSUE TITLE
OTE download error cause sesnsors not updated

### ISSUE THREAD

**Issue by JiriPrchal** [rnovacek/homeassistant_cz_energy_spot_prices#62]
When OTE download error ocures
`2024-10-06 13:06:11.494 ERROR (MainThread) [custom_components.cz_energy_spot_prices.coordinator] OTE request failed 8 times, retrying in 256 seconds`
sensors `sensor.spot_electricity_is_cheapest ...` are not updated.

**Comment by Duncik** [comment]
Same here

**Comment by kkoouu** [comment]
včera byl nějaký výpadek ote-cr.cz, odkud se data stahují, tak proto ... data se objevila až cca v 17 hodin

**Comment by Duncik** [comment]
Potvrzuju dnes ráno už to bylo :-)

**Comment by prchal** [comment]
No ale toto vlákno je o tom, že se nezaply sensory cheapest..., přestože hour order byl 1.

**Comment by Duncik** [comment]
Taak to neviem. Ja to v HA vyhodnocujem tak že porovnávam cenu najlacnejšiu s aktuálnou. A funguje to v pohode. Výhoda je že si viem meniť kolko hodinový "slot" chcem.

**Comment by mbenda1** [comment]
Mě to vypadlo včera (7.10. 14:21) a bohužel do teď nedostávám data, Zkoušel jsem  nové načtení i komplet reinstalaci a nic. Poradit prosím?

**Comment by rnovacek** [comment]
@mbenda1 Tak to je divné. Podívej se prosím do logů a pošli, co tam integrace píše. Web https://www.ote-cr.cz/cs/kratkodobe-trhy/elektrina/denni-trh ti ze stejného počítače funguje?

**Comment by VikyTT** [comment]
Tak já se přidávám k mbenda1, také mi to včera přestalo načítat data. Všechny entity jsou nedostupné.

**Comment by mbenda1** [comment]
Web mi z domácí sítě chodí, HA jede na PI4 ale tím, že to je stejná síť po kabelu tak by to mělo jít také.
Tady je můj detailní log:
------
Tato chyba pochází z vlastní integrace.

Logger: custom_components.cz_energy_spot_prices.coordinator
Zdroj: custom_components/cz_energy_spot_prices/coordinator.py:236
integrace: Czech Energy Spot Prices (dokumentace, problémy)
První výskyt: 08:47:30 (28 výskyty)
Naposledy logováno: 09:39:23

OTE request failed 5 times, retrying in 32 seconds
OTE request failed 6 times, retrying in 64 seconds
OTE request failed 7 times, retrying in 128 seconds
OTE request failed 8 times, retrying in 256 seconds
OTE request failed 9 times, retrying in 512 seconds
Traceback (most recent call last):
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 210, in fetch_data
    electricity_rates, gas_rates = await asyncio.gather(
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/spot_rate.py", line 118, in get_gas_rates
    rates, currency_rates = await asyncio.gather(
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/cnb_rate.py", line 48, in get_current_rates
    self._rates = await self.get_day_rates(day)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/cnb_rate.py", line 31, in get_day_rates
    text = await self.download_rates(day)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/cnb_rate.py", line 22, in download_rates
    async with session.get(self.RATES_URL, params=params) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1355, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 659, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 557, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1002, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 236, in update_data
    self._spot_rate_data = await self.fetch_data()
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 209, in fetch_data
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

**Comment by rnovacek** [comment]
Hm, `TimeoutError`. Zkusil jsem nastavit delší čas než to udělá ten timeout. Zkuste prosím verzi [0.6.4](https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/releases/tag/0.6.4).

**Comment by VikyTT** [comment]
@rnovacek tak jsem to vyzkoušel, a nic
Tady jsou nové logy
Tato chyba pochází z vlastní integrace.

Logger: custom_components.cz_energy_spot_prices.coordinator
Zdroj: custom_components/cz_energy_spot_prices/coordinator.py:262
integrace: Czech Energy Spot Prices (dokumentace, problémy)
První výskyt: 10:10:30 (2 výskyty)
Naposledy logováno: 10:11:39

OTE request failed 1 times, retrying in 2 seconds
Traceback (most recent call last):
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 210, in fetch_data
    electricity_rates, gas_rates = await asyncio.gather(
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/spot_rate.py", line 118, in get_gas_rates
    rates, currency_rates = await asyncio.gather(
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/cnb_rate.py", line 48, in get_current_rates
    self._rates = await self.get_day_rates(day)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/cnb_rate.py", line 31, in get_day_rates
    text = await self.download_rates(day)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/cnb_rate.py", line 22, in download_rates
    async with session.get(self.RATES_URL, params=params) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1355, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 659, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 557, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1002, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1305, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1061, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 262, in _async_update_data
    self._spot_rate_data = await self.fetch_data()
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cz_energy_spot_prices/coordinator.py", line 209, in fetch_data
    async with async_timeout.timeout(30):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

**Comment by rnovacek** [comment]
Tak to je zvláštní. Ještě prosím zkuste, jestli vám jdou načíst kurzy ČNB: https://www.cnb.cz/cs/financni-trhy/devizovy-trh/kurzy-devizoveho-trhu/kurzy-devizoveho-trhu/denni_kurz.txt

**Comment by VikyTT** [comment]
@rnovacek tak tento soubor nejde stáhnout

**Comment by mbenda1** [comment]
U mne oboje stejné jako u @VikyTT

**Comment by mbenda1** [comment]
Vypadá to na nějakou blacklistaci CNB jako takové z některých providerů. nejde mi ani cnb.cz, ale pokud totéž zkusím z VPN tak tak se tam dostanu. Zkusím přepojit HA na jiného providera.

**Comment by VikyTT** [comment]
@rnovacek a @mbenda1 vypadá to tak, pokud se podívám na odkaz přes MT tak to jde, ale přes domácí síť ne. 
Jen otázka bokem, je ten soubor 7.10. Tedy včera, je to správně? Neměl by být na 8.10.?

**Comment by rnovacek** [comment]
> Kurzy devizového trhu jsou vyhlašovány pro běžně obchodované měny, a to každý pracovní den po 14.30 s platností pro aktuální pracovní den a pro případnou následující sobotu, neděli či státní svátek (tj. např. kurz vyhlášený v úterý 23. 12. platí pro úterý 23. 12., státní svátky 24.–26. 12. a pro sobotu 27. 12. a neděli 28. 12.).

Dnešní data budou až odpoledne, čili je to správně.

**Comment by VikyTT** [comment]
> > Kurzy devizového trhu jsou vyhlašovány pro běžně obchodované měny, a to každý pracovní den po 14.30 s platností pro aktuální pracovní den a pro případnou následující sobotu, neděli či státní svátek (tj. např. kurz vyhlášený v úterý 23. 12. platí pro úterý 23. 12., státní svátky 24.–26. 12. a pro sobotu 27. 12. a neděli 28. 12.).
> 
> Dnešní data budou až odpoledne, čili je to správně.

Děkuji za vysvětlení, pak bídě tedy problém v blokaci na webu ČNB což je problém.

**Comment by rnovacek** [comment]
Co máte za postytovatele internetu, který to blokuje? Taky by bylo dobré vědět, jak to blokuje. DNS to přeloží? Například `nslookup cnb.cz` (tohle použije výchozí DNS) a pak `nslookup cnb.cz 1.1.1.1` (použije Cloudflare DNS).

**Comment by mbenda1** [comment]
Já mám pripojen.cz a dále pak CETIN

Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
Name:    cnb.cz
Address:  193.85.3.250

**Comment by mitchmb** [comment]
Ještě možná takový blbý dotaz. Vy co vám to z HA nejde. Nepoužíváte v něm doplněk Adguard Home, který by vám to mohl blokovat? Takhle jsem se tenkrát vyzlobil s nějakou aktivací Windows, až jsem zjistil, že mi to blokuje Adguard (jinak výborný věc).

**Comment by rnovacek** [comment]
Abych se přiznal, tak mě moc řešení nenapadá. Jedině změnit službu, která poskytuje kurzovní informace z ČNB na něco jiného (třeba jen jako fallback). Znáte něco, co má použitelné API bez přihlašování a limitů?

**Comment by mbenda1** [comment]
Zkoušel jsem zadat jen EUR tedy bez přepočtu na CZK ale to nedává nic - tím bych měl vyřadit dotaz na ČNB

**Comment by JiriPrchal** [comment]
Jen se přidám a doplnín. V tu neděli, kdy se nesepnuly senzory, mě to v logu hlásilo asi to stejné. Log už nemám, protože jsem pak aktualizoval na HA 2024.10.1. Po aktualizaci bylo vše z tohoto rozšíření nedostupné. Pomohlo stáhnout znovu.

**Comment by rnovacek** [comment]
Už možná začínám chápat, co se stalo: 

Nefungovalo OTE, takže integrace se pořád dokola snažila stáhnout data. A nejen z OTE, ale i z ČNB. A tím, že se snažilo dlouho a často, někteří uživatelé padli do nějakého blocklistu na webu ČNB (možná dle IP adresy).

Až budu mít chvilku, předělám to, aby stahování z OTE a z ČNB bylo nezávislé.

**Comment by VikyTT** [comment]
> Už možná začínám chápat, co se stalo:
> 
> Nefungovalo OTE, takže integrace se pořád dokola snažila stáhnout data. A nejen z OTE, ale i z ČNB. A tím, že se snažilo dlouho a často, někteří uživatelé padli do nějakého blocklistu na webu ČNB (možná dle IP adresy).
> 
> Až budu mít chvilku, předělám to, aby stahování z OTE a z ČNB bylo nezávislé.

Aha, takže jsme napadli ČNB 😀 

Díky za snahu a super doplněk do HA

**Comment by Duncik** [comment]
Už to vidím večer v správách : Komunita příznivcú slunečné energie podnikla v nedeli nad ránem DDOS útok na ČNB.... 😀

**Comment by mbenda1** [comment]
Zkusím se přes kontakty co mám dostat do ČNB a zjistit více ;-)

**Comment by mbenda1** [comment]
Jako workaround jsem bez dovolení autora ( @rnovacek mi doufám promine ;-) ) přepsal url v \config\custom_components\cz_energy_spot_prices\cnb_rate.py a RATES_URL = jsem přesměroval na svůj interní web, kam jsem si  denni_kurz.txt nakopíroval. sice to není dynamické ale protože přes SPOT ceny řídím prodej FVE tak i přibližný kursy mi stačí. Psal jsem na web@cnb.cz tak snad mne odstraní z blasklistu, nebo z něj časem vypadnu. Po restaru HA se to opět rozběhlo, byť se statickým kurzem.

Jinak díky moc za super doplněk, až když mi přestal fungovat, došlo mi jak moc je pro mne důležitý!

**Comment by pezinek** [comment]
> Až budu mít chvilku, předělám to, aby stahování z OTE a z ČNB bylo nezávislé.

možná by stálo za to udělat ten kurz jako další senzor a nechat ho při startu načíst z DB home-assistantu, a update z webu naschedulovat teprve az potom co ten kurz bude "zastaralý".
