### ISSUE TITLE
Python error when install the integration

### ISSUE THREAD

**Issue by trnxtrnx** [rnovacek/homeassistant_cz_energy_spot_prices#79]
Hello! 
I have just installed the integration and some python errors appears in hass log. 
I tried to use release 0.6.4 and also 0.7.0b1. Still same error.
I am running HA 2024.12.4

`hass-1  | 2024-12-22 17:27:51.913 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/root/.netrc',) inside the event loop by custom integration 'cz_energy_spot_prices' at custom_components/cz_energy_spot_prices/spot_rate.py, line 94: async with session.post(self.OTE_PUBLIC_URL, data=query) as response: (offender: /usr/local/lib/python3.13/netrc.py, line 74: with open(file, encoding="utf-8") as fp:), please create a bug report at https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/issues
hass-1  | For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
hass-1  | Traceback (most recent call last):
hass-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
hass-1  |   File "<frozen runpy>", line 88, in _run_code
hass-1  |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
hass-1  |     sys.exit(main())
hass-1  |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
hass-1  |     exit_code = runner.run(runtime_conf)
hass-1  |   File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
hass-1  |     return loop.run_until_complete(setup_and_run_hass(runtime_config))
hass-1  |   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
hass-1  |     self.run_forever()
hass-1  |   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
hass-1  |     self._run_once()
hass-1  |   File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
hass-1  |     handle._run()
hass-1  |   File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
hass-1  |     self._context.run(self._callback, *self._args)
hass-1  |   File "/config/custom_components/cz_energy_spot_prices/spot_rate.py", line 106, in get_electricity_rates
hass-1  |     return await self._get_rates(query, unit, has_hours=True)
hass-1  |   File "/config/custom_components/cz_energy_spot_prices/spot_rate.py", line 133, in _get_rates
hass-1  |     text = await self._download(query)
hass-1  |   File "/config/custom_components/cz_energy_spot_prices/spot_rate.py", line 94, in _download
hass-1  |     async with session.post(self.OTE_PUBLIC_URL, data=query) as response:`

**Comment by rnovacek** [comment]
It seems to be complaining about `/root/.netrc` file. Do you have such file on your system? What's the file content?

**Comment by trnxtrnx** [comment]
I check it twice but I dont have this file neither in system nor in hass docker container..

**Comment by rnovacek** [comment]
Thanks for the reference, would be pretty tough to solve without it. I have reverted the change.
